"""update_payments_table_columns

Revision ID: c3fdfc671ef3
Revises: 0266d5fabb22
Create Date: 2026-07-20 17:07:02.302010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fdfc671ef3'
down_revision: Union[str, None] = '0266d5fabb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_requests',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('razorpay_refund_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('defective','wrong_item','not_as_described','changed_mind','other')", name='ck_return_requests_reason'),
    sa.CheckConstraint("status IN ('pending','approved','rejected','refund_initiated','refund_completed')", name='ck_return_requests_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=True)
    op.create_index(op.f('ix_return_requests_user_id'), 'return_requests', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_review')
    )
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.alter_column('cart_items', 'cart_token',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_unique_constraint('uq_token_cart_product', 'cart_items', ['cart_token', 'product_id'])
    op.create_unique_constraint('uq_user_cart_product', 'cart_items', ['user_id', 'product_id'])
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_constraint('categories_slug_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('google_auth_codes', sa.Column('code_hash', sa.String(length=64), nullable=True))
    op.drop_index('ix_google_auth_codes_code', table_name='google_auth_codes')
    op.create_index(op.f('ix_google_auth_codes_code_hash'), 'google_auth_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_google_auth_codes_user_id'), 'google_auth_codes', ['user_id'], unique=False)
    op.drop_column('google_auth_codes', 'code')
    op.add_column('orders', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('razorpay_refund_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('payments', 'razorpay_payment_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.drop_constraint('payments_razorpay_order_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.drop_column('payments', 'razorpay_signature')
    op.add_column('products', sa.Column('compare_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.drop_column('products', 'disabled_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('disabled_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('products', 'status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('products', 'compare_price')
    op.add_column('payments', sa.Column('razorpay_signature', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.create_unique_constraint('payments_razorpay_order_id_key', 'payments', ['razorpay_order_id'])
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('payments', 'razorpay_payment_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('payments', 'refunded_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'refund_amount')
    op.drop_column('payments', 'razorpay_refund_id')
    op.drop_column('orders', 'cancel_reason')
    op.add_column('google_auth_codes', sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_google_auth_codes_user_id'), table_name='google_auth_codes')
    op.drop_index(op.f('ix_google_auth_codes_code_hash'), table_name='google_auth_codes')
    op.create_index('ix_google_auth_codes_code', 'google_auth_codes', ['code'], unique=True)
    op.drop_column('google_auth_codes', 'code_hash')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_unique_constraint('categories_slug_key', 'categories', ['slug'])
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'description')
    op.drop_constraint('uq_user_cart_product', 'cart_items', type_='unique')
    op.drop_constraint('uq_token_cart_product', 'cart_items', type_='unique')
    op.alter_column('cart_items', 'cart_token',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_return_requests_user_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_table('return_requests')
    # ### end Alembic commands ###
